-- Admin-only, same convention as get_song_duplicate_groups(). Groups on
-- normalized name AND normalized address together, not name alone --
-- unlike songs (title+artist), a venue name by itself isn't a safe
-- duplicate signal: plenty of real, genuinely different venues share a
-- generic name ("The Red Lion", "Village Hall") in different towns.
-- Requiring the address to match too (also normalized, so formatting
-- noise doesn't defeat it) is what keeps this from ever suggesting two
-- unrelated real venues get merged. A venue with no address at all is
-- excluded from grouping entirely, for the same reason.
create or replace function public.get_venue_duplicate_groups()
returns table (
  norm_key text,
  id uuid,
  name text,
  address text,
  has_contact boolean,
  has_phone boolean,
  has_notes boolean,
  has_coords boolean,
  gig_count bigint
)
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  if not public.is_admin() then
    raise exception 'Only admins can view venue duplicate groups';
  end if;

  return query
  with normalized as (
    select
      v.id, v.name, v.address, v.contact_name, v.phone, v.load_in_notes, v.latitude, v.longitude,
      trim(regexp_replace(regexp_replace(regexp_replace(lower(v.name), '[’`´'']', '', 'g'), '[^a-z0-9\s]', ' ', 'g'), '\s+', ' ', 'g')) as norm_name,
      trim(regexp_replace(regexp_replace(regexp_replace(lower(coalesce(v.address, '')), '[’`´'']', '', 'g'), '[^a-z0-9\s]', ' ', 'g'), '\s+', ' ', 'g')) as norm_address
    from public.venues v
  ),
  grouped as (
    select n.norm_name, n.norm_address
    from normalized n
    where n.norm_address <> ''
    group by n.norm_name, n.norm_address
    having count(*) > 1
  )
  select
    n.norm_name || '|' || n.norm_address,
    n.id, n.name, n.address,
    (n.contact_name is not null and n.contact_name <> ''),
    (n.phone is not null and n.phone <> ''),
    (n.load_in_notes is not null and n.load_in_notes <> ''),
    (n.latitude is not null and n.longitude is not null),
    (select count(distinct g.id) from public.gigs g where g.venue_id = n.id)
  from normalized n
  join grouped g on g.norm_name = n.norm_name and g.norm_address = n.norm_address
  order by n.norm_name, n.norm_address, 9 desc;
end;
$$;

grant execute on function public.get_venue_duplicate_groups() to authenticated;
revoke execute on function public.get_venue_duplicate_groups() from public;

-- Admin-only merge: backfills any field the winner is missing from the
-- loser, repoints gigs.venue_id, drops the loser's cached nearby-places
-- rows (disposable -- regenerated by the existing nightly sweep, and the
-- winner shares the same real-world address so its own cache is equally
-- valid), then deletes the loser.
create or replace function public.merge_duplicate_venues(p_winner_id uuid, p_loser_id uuid)
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  if not public.is_admin() then
    raise exception 'Only admins can merge venues';
  end if;

  if p_winner_id = p_loser_id then
    raise exception 'Cannot merge a venue into itself';
  end if;

  update public.venues w
    set contact_name = coalesce(nullif(w.contact_name, ''), l.contact_name),
        contact_title = coalesce(nullif(w.contact_title, ''), l.contact_title),
        phone = coalesce(nullif(w.phone, ''), l.phone),
        email = coalesce(nullif(w.email, ''), l.email),
        website = coalesce(nullif(w.website, ''), l.website),
        load_in_notes = coalesce(nullif(w.load_in_notes, ''), l.load_in_notes),
        latitude = coalesce(w.latitude, l.latitude),
        longitude = coalesce(w.longitude, l.longitude),
        stage_width_m = coalesce(w.stage_width_m, l.stage_width_m),
        stage_depth_m = coalesce(w.stage_depth_m, l.stage_depth_m),
        has_stage_riser = coalesce(w.has_stage_riser, l.has_stage_riser)
    from public.venues l
    where w.id = p_winner_id and l.id = p_loser_id;

  update public.gigs set venue_id = p_winner_id where venue_id = p_loser_id;

  delete from public.venue_nearby_places where venue_id = p_loser_id;

  delete from public.venues where id = p_loser_id;
end;
$$;

grant execute on function public.merge_duplicate_venues(uuid, uuid) to authenticated;
revoke execute on function public.merge_duplicate_venues(uuid, uuid) from public;
